Use MariaDB account and secret in Designate controllers
openstack-k8s-operators/designate-operator pull request #195
Opened 2024-07-15 13:14 UTC by omersch381

So far, MariaDB account and secret were added to specs and types, and were used in designate_controller.go, but weren't used in the rest of the controllers.

This patch uses MariaDB in the rest of the controllers.

2024-07-16 13:41 UTC, omersch381 commented
/retest

2024-07-19 16:06 UTC, gthiemonge requested changes

2024-07-22 09:12 UTC, omersch381 commented on api/v1beta1/designate_types.go
> -	DatabaseHostname string `json:"databaseHostname,omitempty"`
Done.

2024-07-26 17:13 UTC, beagles commented
/lgtm

2024-07-28 15:47 UTC, omersch381 commented
/retest

2024-07-28 16:54 UTC, merged